name: Build and Deploy Storybook

on:
  push:
    branches:
      - main
    paths: ['src/stories/**', 'src/components/**']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.1'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build Storybook files
        run: npm run build-storybook
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.4
        with:
          folder: storybook-static
          clean: true
          target-folder: docs
